title: MCU course
tagline: ESP32 Lectures

author:
  name: Richard Kuo
  url: https://www.facebook.com/richard.kuo.168

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme  

paginate: 3

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
#theme: jekyll-theme-hydure
